// npm run asset -- <id> <command>
//
// One building made into a finished 3D asset, step by step, with its whole
// state kept in assets3d/<id>/ (see assets3d/README.md): what it should be
// (spec, geometry rules, materials, textures), what was decided, what failed,
// what is wrong now, screenshots of every round and the code changes made.
//
//   status    rewrite changes.md (the generator's commits and uncommitted edits) and STATE.md
//             (everything in one file, for a reviewer: a person or another model)
//   shots     render the game's model in Blender from the reference's angle, put it beside
//             the reference, and keep the picture in screenshots/
//   textures  what textures the asset needs, which exist, and what is still to be painted
//
// The model is the game's own (src/render/build3d): a round of work is a change to the
// generator, then `shots`, then a note in problems.md / decisions.md / failed.md.

import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

interface Asset {
  id: string;
  title: string;
  /** The game building it is: type, seed, size and look (the Large farm's is "upgraded"). */
  type: string;
  seed: number;
  size: 1 | 2 | 3;
  look: string;
  /** The picture it is made from (not in git: .art-raw is local). */
  reference: string;
  /** The files that make it: the changes to these are its history. */
  generator: string[];
  /** Since when (date) the generator's commits belong to this asset. */
  since: string;
}

const [id, command] = process.argv.slice(2);
const dir = join('assets3d', id ?? '');
if (!id || !command || !existsSync(join(dir, 'asset.json'))) {
  const ids = existsSync('assets3d') ? readdirSync('assets3d').filter((d) => existsSync(join('assets3d', d, 'asset.json'))) : [];
  console.error(`usage: npm run asset -- <${ids.join('|') || 'id'}> <status|shots|textures>`);
  process.exit(2);
}
const asset: Asset = JSON.parse(readFileSync(join(dir, 'asset.json'), 'utf8'));
const read = (f: string) => (existsSync(join(dir, f)) ? readFileSync(join(dir, f), 'utf8').trim() : '');
const git = (...args: string[]) => execFileSync('git', args, { encoding: 'utf8' }).trim();

// --- status --------------------------------------------------------------------------

function changes(): string {
  const log = git('log', `--since=${asset.since}`, '--date=short', '--format=- %ad `%h` %s', '--', ...asset.generator);
  const stat = git('diff', '--stat', 'HEAD', '--', ...asset.generator);
  const text = [
    `# Code changes: ${asset.title}`,
    '',
    'Written by `npm run asset -- ' + `${id} status\`. The generator: ${asset.generator.map((f) => `\`${f}\``).join(', ')}.`,
    '',
    '## Commits',
    log || '(none yet)',
    '',
    '## Not committed yet',
    stat ? '```\n' + stat + '\n```' : '(nothing)',
  ].join('\n');
  writeFileSync(join(dir, 'changes.md'), text + '\n');
  return text;
}

function shotsList(): string[] {
  const d = join(dir, 'screenshots');
  return existsSync(d) ? readdirSync(d).filter((f) => f.endsWith('.webp')).sort() : [];
}

function status(): void {
  const c = changes();
  const shots = shotsList();
  const tex = textureRows();
  const section = (title: string, file: string) => `\n\n---\n\n<!-- ${file} -->\n` + (read(file) || `# ${title}\n\n(empty)`);
  const state = [
    `# Project state: ${asset.title}`,
    '',
    `Generated by \`npm run asset -- ${id} status\` from the files in this folder; edit those, not this.`,
    '',
    `- **Building:** \`${asset.type}\`, seed ${asset.seed}, size ${asset.size}, look \`${asset.look}\``,
    `- **Reference:** \`${asset.reference}\` (local only)`,
    `- **Procedural generator:** ${asset.generator.map((f) => `\`${f}\``).join(', ')}`,
    `- **Latest screenshot:** ${shots.length ? `\`screenshots/${shots[shots.length - 1]}\`` : '(none yet: run `shots`)'} (${shots.length} in all)`,
    `- **Textures:** ${tex.filter((t) => t.have).length} of ${tex.length} made`,
    section('Building specification', 'spec.md'),
    section('Geometry rules', 'geometry.md'),
    section('Materials', 'materials.md'),
    '\n\n---\n\n# Texture requirements\n\n' + tex.map((t) => `- ${t.have ? '[x]' : '[ ]'} \`${t.name}\`: ${t.what}`).join('\n'),
    section('Current problems', 'problems.md'),
    section('Decisions made', 'decisions.md'),
    section('Failed experiments', 'failed.md'),
    '\n\n---\n\n# Screenshots\n\n' + (shots.map((s) => `- \`screenshots/${s}\``).join('\n') || '(none yet)'),
    '\n\n---\n\n' + c,
  ].join('\n');
  writeFileSync(join(dir, 'STATE.md'), state + '\n');
  console.log(state);
}

// --- textures ------------------------------------------------------------------------

interface TextureReq {
  name: string;
  what: string;
  prompt: string;
}

function textureRows(): Array<TextureReq & { have: boolean }> {
  const f = join(dir, 'textures.json');
  if (!existsSync(f)) return [];
  const reqs: TextureReq[] = JSON.parse(readFileSync(f, 'utf8'));
  return reqs.map((r) => ({ ...r, have: existsSync(join('public/textures', `${r.name}.webp`)) }));
}

function textures(): void {
  const rows = textureRows();
  for (const t of rows) console.log(`${t.have ? 'have ' : 'TO DO'}  ${t.name.padEnd(10)} ${t.what}`);
  const todo = rows.filter((t) => !t.have);
  if (todo.length) {
    const job = join('.art-raw', 'asset', id, 'textures.job.json');
    mkdirSync(join('.art-raw', 'asset', id), { recursive: true });
    writeFileSync(job, JSON.stringify(todo.map((t) => ({ name: t.name, prompt: t.prompt })), null, 2));
    console.log(`\n${todo.length} to paint: ${job} (FLUX on the GPU, then npm run paint:tile -- <png> <name>; tools/paint/README.md)`);
  }
}

// --- shots ---------------------------------------------------------------------------

async function shots(): Promise<void> {
  const raw = join('.art-raw', 'asset', id, 'render');
  const job = join('.art-raw', 'asset', id, 'render.job.json');
  mkdirSync(raw, { recursive: true });
  writeFileSync(
    job,
    JSON.stringify({
      id: `asset.${id}`,
      views: ['threequarter'],
      samples: 48,
      emissive_samples: 8,
      source: { method: 'render3d', models: [{ name: 'Blender', version: '4.5 LTS', licence: 'GPL-3.0 (tool; output is ours)' }], author: 'tools/asset', notes: asset.title, date: new Date().toISOString().slice(0, 10) },
    }),
  );
  const env = { ...process.env, BUILDING: asset.type, SEED: String(asset.seed), SIZE: String(asset.size), STYLE: 'painterly' };
  const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const r = spawnSync(npm, ['run', 'art:render', '--', 'tools/building-gen/scenes/building.py', job, '--raw', raw, '--no-pack'], { env, stdio: 'inherit', shell: process.platform === 'win32' });
  if (r.status !== 0) throw new Error('the Blender render failed');

  // the reference, then the model from its angle and from the street, all as tall as one another
  const H = 640;
  const pics: Buffer[] = [];
  const add = async (file: string, label: string) => {
    if (!existsSync(file)) return;
    // renders have empty margins: cut them off first (a step of its own: sharp applies trim after resize in one chain)
    const trimmed = await sharp(file).trim().toBuffer();
    const img = await sharp(trimmed).flatten({ background: '#f4efe4' }).resize({ height: H }).toBuffer();
    const { width } = await sharp(img).metadata();
    const caption = Buffer.from(`<svg width="${width}" height="34"><rect width="100%" height="100%" fill="#2b2118"/><text x="10" y="23" font-family="Georgia" font-size="18" fill="#f3ead8">${label}</text></svg>`);
    pics.push(await sharp(img).extend({ top: 34, background: '#2b2118' }).composite([{ input: caption, top: 0, left: 0 }]).png().toBuffer());
  };
  await add(asset.reference, 'reference');
  await add(join(raw, 'threequarter', asset.look, 'color.png'), 'model, three-quarter');
  const metas = await Promise.all(pics.map((p) => sharp(p).metadata()));
  const W = metas.reduce((s, m) => s + (m.width ?? 0) + 8, 0);
  let x = 0;
  const sheet = sharp({ create: { width: W, height: H + 34, channels: 3, background: '#2b2118' } }).composite(
    pics.map((p, i) => {
      const at = { input: p, top: 0, left: x };
      x += (metas[i].width ?? 0) + 8;
      return at;
    }),
  );
  mkdirSync(join(dir, 'screenshots'), { recursive: true });
  const stamp = new Date().toISOString().slice(0, 16).replace(/[-:]/g, '').replace('T', '-');
  // the committed screenshots show the model only (the reference stays local); the sheet with it is local
  const local = join('.art-raw', 'asset', id, `compare-${stamp}.png`);
  await sheet.png().toFile(local);
  const own = join(raw, 'threequarter', asset.look, 'color.png');
  const out = join(dir, 'screenshots', `${stamp}.webp`);
  await sharp(await sharp(own).trim().toBuffer()).flatten({ background: '#f4efe4' }).resize({ height: H }).webp({ quality: 85 }).toFile(out);
  console.log(`compare: ${local}\nscreenshot: ${out}`);
}

if (command === 'status') status();
else if (command === 'textures') textures();
else if (command === 'shots') await shots();
else {
  console.error(`unknown command ${command}: status | shots | textures`);
  process.exit(2);
}
